// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrMf5ntqTCiHa8f35KM7MxWt9ib3AYLN4',
    appId: '1:804380081468:web:a9056614991ed277333239',
    messagingSenderId: '804380081468',
    projectId: 'price-ninja-raman-2026',
    authDomain: 'price-ninja-raman-2026.firebaseapp.com',
    storageBucket: 'price-ninja-raman-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnmLJmU5SPAqnQXcaco649TQQTkzZWDkg',
    appId: '1:804380081468:android:dc4426bb4af44d45333239',
    messagingSenderId: '804380081468',
    projectId: 'price-ninja-raman-2026',
    storageBucket: 'price-ninja-raman-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl122RaQn5Kp05powqbwN71hHgOqDvhNs',
    appId: '1:804380081468:ios:848c971c600935b9333239',
    messagingSenderId: '804380081468',
    projectId: 'price-ninja-raman-2026',
    storageBucket: 'price-ninja-raman-2026.firebasestorage.app',
    iosBundleId: 'com.priceninja.priceNinja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrMf5ntqTCiHa8f35KM7MxWt9ib3AYLN4',
    appId: '1:804380081468:web:677caf8eaeda70dd333239',
    messagingSenderId: '804380081468',
    projectId: 'price-ninja-raman-2026',
    authDomain: 'price-ninja-raman-2026.firebaseapp.com',
    storageBucket: 'price-ninja-raman-2026.firebasestorage.app',
  );
}
